apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-syncagent
rules:
  # get the LogicalCluster
  - apiGroups:
      - core.kcp.io
    resources:
      - logicalclusters
    resourceNames:
      - cluster
    verbs:
      - get
  # watch the APIExportEndpointSlice (optional, could also be in a different workspace)
  - apiGroups:
      - apis.kcp.io
    resources:
      - apiexportendpointslices
    resourceNames:
      - myapiexport
    verbs:
      - get
      - list
      - watch
  # manage its APIExport
  - apiGroups:
      - apis.kcp.io
    resources:
      - apiexports
    resourceNames:
      - myapiexport
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  # issue events for APIExports
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - create
      - patch
      - update
  # manage APIResourceSchemas
  - apiGroups:
      - apis.kcp.io
    resources:
      - apiresourceschemas
    verbs:
      - get
      - list
      - watch
      - create
  # access the virtual workspace
  - apiGroups:
      - apis.kcp.io
    resources:
      - apiexports/content
    resourceNames:
      - myapiexport
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-syncagent:system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: my-syncagent
subjects:
  - kind: ServiceAccount
    namespace: default
    name: service-provider

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-syncagent:access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kcp:workspace:access
subjects:
  - kind: ServiceAccount
    namespace: default
    name: service-provider
