repositories:
  - name: kcp
    url: https://kcp-dev.github.io/helm-charts

releases:
  - name: myservice-syncagent
    namespace: default
    atomic: true
    createNamespace: true
    chart: kcp/api-syncagent
    version: 0.3.1
    labels:
      id: myservice-syncagent
    values:
      - replicas: 1
        enableLeaderElection: false
        crds:
          enabled: true
        apiExportName: myorg.com
        agentName: myservice-syncagent
        kcpKubeconfig: kubeconfig-kcp-provider

# TODO no tags for kdp releases which solve the issue due to no tags
# => could be fixed via eg v0.9.0-g91c78b4293638d06c56d410fa89a107a5097bd61
# => but going with 0.3.1 is also fine
# https://quay.io/repository/kubermatic/developer-platform?tab=tags
