repositories:
  - name: kcp
    url: https://kcp-dev.github.io/helm-charts

releases:
  - name: myservice-syncagent
    namespace: default
    atomic: true
    createNamespace: true
    chart: kcp/api-syncagent
    version: 0.3.1
    labels:
      id: myservice-syncagent
    values:
      - crds:
          enabled: true
        apiExportName: myorg.com
        agentName: myservice-syncagent
        kcpKubeconfig: kubeconfig-kcp-provider
