repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: dex
    url: https://charts.dexidp.io
  - name: kcp
    url: https://kcp-dev.github.io/helm-charts

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    atomic: true
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: 4.12.2
    labels:
      id: ingress-nginx
    values:
      - /training/platform-cluster/helm/values_ingress-nginx.yaml
  - name: cert-manager
    namespace: cert-manager
    atomic: true
    createNamespace: true
    chart: oci://quay.io/jetstack/charts/cert-manager
    version: v1.17.4
    labels:
      id: cert-manager
    values:
      - /training/platform-cluster/helm/values_cert-manager.yaml
  - name: dex
    namespace: kdp-system
    atomic: true
    createNamespace: true
    chart: dex/dex
    labels:
      id: dex
    version: 0.23.0
    values:
      - /training/platform-cluster/helm/values_dex.yaml
  - name: kcp
    namespace: kdp-system
    atomic: true
    createNamespace: true
    chart: kcp/kcp
    labels:
      id: kcp
    # TODO version upgrade? 0.12.3 available but ran into issues
    version: 0.11.1
    values:
      - /training/platform-cluster/helm/values_kcp.yaml
  - name: developer-platform
    namespace: kdp-system
    atomic: true
    createNamespace: true
    chart: oci://quay.io/kubermatic/helm-charts/developer-platform
    labels:
      id: developer-platform
    version: 0.9.0
    values:
      - /training/platform-cluster/helm/values_developer-platform.yaml
  - name: developer-platform-dashboard
    namespace: kdp-system
    atomic: true
    createNamespace: true
    chart: oci://quay.io/kubermatic/helm-charts/developer-platform-dashboard
    labels:
      id: developer-platform-dashboard
    version: 0.9.0
    values:
      - /training/platform-cluster/helm/values_developer-platform-dashboard.yaml
