apiVersion: v1
items:
  - apiVersion: apis.kcp.io/v1alpha1
    kind: APIResourceSchema
    metadata:
      annotations:
        kcp.io/cluster: 35mfqts1yrk1ri33
        syncagent.kcp.io/agent-name: test-syncagent
        syncagent.kcp.io/source-generation: "1"
      creationTimestamp: "2025-09-17T12:22:17Z"
      generation: 1
      labels:
        syncagent.kcp.io/agent-name: test-syncagent
        syncagent.kcp.io/api-group: myapigroup.com
      name: v1d2cf8df.helloworlds.example.com
      resourceVersion: "107334"
      uid: 00e39398-c8c6-4367-8b58-7c2b5a319cbe
    spec:
      group: example.com
      nameValidation: DNS1123Subdomain
      names:
        kind: HelloWorld
        listKind: HelloWorldList
        plural: helloworlds
        shortNames:
          - hw
        singular: helloworld
      scope: Namespaced
      versions:
        - name: v1
          schema:
            properties:
              spec:
                properties:
                  message:
                    type: string
                  recipient:
                    type: string
                type: object
            type: object
          served: true
          storage: true
          subresources: {}
kind: List
metadata:
  resourceVersion: ""
