repositories:
  - name: kcp
    url: https://kcp-dev.github.io/helm-charts

releases:
  - name: myservice-syncagent
    namespace: default
    atomic: true
    createNamespace: true
    chart: kcp/api-syncagent
    version: 0.6.0
    labels:
      id: myservice-syncagent
    values:
      - replicas: 1
        enableLeaderElection: false
        crds:
          enabled: true
        apiExportEndpointSliceName: myapiexport
        agentName: myservice-syncagent
        kcpKubeconfig: kubeconfig-kcp-provider
