repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: cert-manager
    namespace: cert-manager
    atomic: true
    createNamespace: true
    chart: oci://quay.io/jetstack/charts/cert-manager
    version: v1.17.4
    values:
      - crds:
          enabled: true
  - name: ingress-nginx
    namespace: ingress-nginx
    atomic: true
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: 4.12.2
    values:
      - controller:
          replicaCount: 2
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 3
            targetCPUUtilizationPercentage: 80
            targetMemoryUtilizationPercentage: 80
